import Mathlib.Tactic.Ring
import Mathlib.Tactic.NoncommRing

/-!
# Two bounded steps of III (2.10)

The book works in the commutative subring generated by one element `a`.
For `n = 2`, its binomial polynomial is
`f₂(a) = a⁴ + 4a³(1-a) + 6a²(1-a)² = 3a⁴ - 8a³ + 6a²`.
We factor its defect and its difference from `a`; thus an element whose
idempotency defect has square zero is corrected to an idempotent.
This proves the displayed step for nilpotency index at most two, not
arbitrary nilpotency, completeness, or the full lifting theorem.

Separately, the book replaces the next approximate idempotent by
`b = (1-e)a(1-e)`. The two orthogonality identities hold in every ring,
without assuming that `a` commutes with the existing idempotent `e`.
-/

namespace Bass1973

def liftPolynomial₂ {R : Type*} [CommRing R] (a : R) : R :=
  3 * a ^ 4 - 8 * a ^ 3 + 6 * a ^ 2

theorem liftPolynomial₂_defect {R : Type*} [CommRing R] (a : R) :
    liftPolynomial₂ a ^ 2 - liftPolynomial₂ a =
      (a * (1 - a)) ^ 2 * (9 * a ^ 4 - 30 * a ^ 3 + 31 * a ^ 2 - 4 * a - 6) := by
  unfold liftPolynomial₂
  ring

theorem liftPolynomial₂_congruence {R : Type*} [CommRing R] (a : R) :
    liftPolynomial₂ a - a = a * (1 - a) * (-3 * a ^ 2 + 5 * a - 1) := by
  unfold liftPolynomial₂
  ring

theorem squareZeroDefect_lifts {R : Type*} [CommRing R] (a : R)
    (h : (a * (1 - a)) ^ 2 = 0) :
    liftPolynomial₂ a * liftPolynomial₂ a = liftPolynomial₂ a := by
  have hf := liftPolynomial₂_defect a
  rw [h, zero_mul] at hf
  exact sub_eq_zero.mp (by simpa only [pow_two] using hf)

theorem corner_left_orthogonal {R : Type*} [Ring R] (e a : R)
    (he : e * e = e) : e * ((1 - e) * a * (1 - e)) = 0 := by
  have h : e * (1 - e) = 0 := by rw [mul_sub, mul_one, he, sub_self]
  rw [← mul_assoc, ← mul_assoc, h, zero_mul, zero_mul]

theorem corner_right_orthogonal {R : Type*} [Ring R] (e a : R)
    (he : e * e = e) : ((1 - e) * a * (1 - e)) * e = 0 := by
  have h : (1 - e) * e = 0 := by rw [sub_mul, one_mul, he, sub_self]
  rw [mul_assoc, h, mul_zero]

#print axioms liftPolynomial₂_defect
#print axioms liftPolynomial₂_congruence
#print axioms squareZeroDefect_lifts
#print axioms corner_left_orthogonal
#print axioms corner_right_orthogonal

end Bass1973
