#set document(title: "Алгебраическая К-теория", author: "Х. Басс", date: none)
#import "book-style.typ": book-style
#import "frontmatter/cover.typ": cover
#import "frontmatter/english-title.typ": english-title
#import "frontmatter/title.typ": title-page
#import "frontmatter/publication.typ": (
  blank-page, publication-page, publisher-page,
)
#show: book-style
#cover()
#counter(page).update(1)
#publisher-page()
#english-title()
#title-page()
#publication-page()
#include "00-russian-preface.typ"
#include "01-preface.typ"
#include "02-introduction.typ"
#include "03-dependencies.typ"
#include "04-notation.typ"
#blank-page()
#include "05-preliminaries.typ"
#include "10-category-algebra.typ"
#include "11-categories-functors.typ"
#include "12-representable-functors.typ"
#include "13-additive-categories.typ"
#include "14-abelian-categories.typ"
#include "15-complexes-homology.typ"
#include "16-projective-resolutions.typ"
#include "17-adjoint-functors.typ"
#include "18-direct-limits.typ"
#include "20-module-categories.typ"
#include "21-module-category-characterization.typ"
#include "22-right-continuous-functors.typ"
#include "23-module-equivalences.typ"
#include "24-equivalence-from-module.typ"
#include "25-picard-group.typ"
#include "26-module-categories-notes.typ"
#include "30-rings-modules.typ"
#include "31-semisimplicity-wedderburn.typ"
#include "32-jacobson-radical-idempotents.typ"
#include "33-chain-conditions-spectrum-dimension.typ"
#include "34-localization-support.typ"
#include "35-integral-elements.typ"
#include "36-homological-dimension.typ"
#include "37-rank-picard-krull.typ"
#include "38-orders-semisimple-algebras.typ"
#include "39-rings-modules-notes.typ"
#include "06-stable-structure.typ"
#include "100-stable-projective-structure.typ"
#include "101-semilocal-projective-modules.typ"
#include "102-serres-theorem.typ"
#include "103-cancellation-elementary-automorphisms.typ"
#include "104-affine-module-group.typ"
#include "105-free-products-firs-cohns-theorem.typ"
#include "106-seshadris-theorem.typ"
#include "107-stable-projective-notes.typ"
#include "110-stable-linear-groups.typ"
#include "111-elementary-matrices-congruence-subgroups.typ"
#include "112-normal-subgroups-relative-k1.typ"
#include "113-stable-rank-conditions.typ"
#include "114-linear-stability-main-theorems.typ"
#include "115-linear-stability-first-proof.typ"
#include "116-linear-stability-homomorphism-construction.typ"
#include "117-linear-stability-homomorphism-normalizer.typ"
#include "118-linear-stability-final-proof.typ"
#include "119-semilocal-linear-groups.typ"
#include "120-linear-group-finite-generation.typ"
#include "121-stable-linear-groups-notes.typ"
#include "130-mennicke-symbols.typ"
#include "131-universal-mennicke-symbols.typ"
#include "132-mennicke-main-theorems.typ"
#include "133-kubotas-theorem.typ"
#include "134-mennicke-arithmetic-proof.typ"
#include "135-relative-mennicke-symbols.typ"
#include "136-dedekind-reciprocity-laws.typ"
#include "137-number-field-reciprocity.typ"
#include "138-curve-reciprocity.typ"
#include "139-mennicke-symbols-notes.typ"
#include "07-algebraic-k-theory.typ"
#include "140-exact-k-sequences.typ"
#include "141-product-category-k-groups.typ"
#include "142-cofinal-functors.typ"
#include "143-fiber-product-categories.typ"
#include "144-mayer-vietoris-sequence.typ"
#include "145-cofinal-functor-exact-sequence.typ"
#include "146-excision-isomorphisms.typ"
#include "147-exact-k-sequences-notes.typ"
#include "150-abelian-k-theory.typ"
#include "151-abelian-grothendieck-whitehead.typ"
#include "152-cofinal-exact-k-sequence.typ"
#include "153-devissage.typ"
#include "154-resolution-reduction.typ"
#include "155-quotient-categories.typ"
#include "156-roberts-theorem.typ"
#include "157-abelian-k-theory-notes.typ"
#include "08-projective-k-theory.typ"
#include "160-projective-k-theory.typ"
#include "161-projective-k-functoriality.typ"
#include "162-g-groups-cartan-maps.typ"
#include "163-rank-determinant-picard.typ"
#include "164-projective-k-stability.typ"
#include "165-milnor-fiber-products.typ"
#include "166-projective-k-localization.typ"
#include "167-finite-projective-resolutions-k-theory.typ"
#include "168-symmetric-exterior-algebras.typ"
#include "169-projective-k-theory-notes.typ"
#include "170-arithmetic-finiteness.typ"
#include "171-swan-triangle-cartan-condition.typ"
#include "172-finiteness-of-class-number.typ"
#include "173-finite-generation-k-g-groups.typ"
#include "174-arithmetic-finiteness-notes.typ"
#include "180-finite-group-induction.typ"
#include "181-group-rings-restriction-induction.typ"
#include "182-frobenius-functors-modules.typ"
#include "183-induction-exponents.typ"
#include "184-classical-induction-theorems.typ"
#include "185-group-ring-k0-g0-applications.typ"
#include "186-abelian-group-ring-conductor.typ"
#include "187-group-ring-k1-g1-applications.typ"
#include "188-finite-group-induction-notes.typ"
#include "190-polynomial-fundamental-theorem.typ"
#include "191-endomorphism-characteristic-sequence.typ"
#include "192-hilbert-syzygy-theorem.typ"
#include "193-serre-polynomial-k0.typ"
#include "194-grothendieck-polynomial-g0.typ"
#include "195-polynomial-linearization.typ"
#include "196-nilpotent-endomorphisms.typ"
#include "197-fundamental-theorem.typ"
#include "198-long-mayer-vietoris.typ"
#include "199-projective-line-k0.typ"
#include "200-abelian-group-rings.typ"
#include "201-gersten-stallings-free-products.typ"
#include "202-polynomial-fundamental-theorem-notes.typ"
#include "210-reciprocity-finiteness.typ"
#include "211-dedekind-localization-sequence.typ"
#include "212-reciprocity-functoriality.typ"
#include "213-reciprocity-finiteness-examples.typ"
#include "214-reciprocity-finiteness-notes.typ"
#include "220-vector-bundles-projective-modules.typ"
#include "221-vector-bundles.typ"
#include "222-normal-space-bundle-sections.typ"
#include "223-compact-space-section-equivalence.typ"
#include "224-vector-bundle-stability.typ"
#include "225-suspension-bundles-linear-groups.typ"
#include "226-topological-k-theory.typ"
#include "70-problems.typ"
#include "80-bibliography.typ"
#include "81-additional-bibliography.typ"
#include "82-editorial-bibliography.typ"
#import "main-defs.typ": editorial-bibliography
#editorial-bibliography
#include "90-name-index.typ"
#include "91-subject-index.typ"
#include "92-symbol-index.typ"
#outline(title: [Оглавление], depth: 2)
#include "95-colophon.typ"
#include "96-back-cover.typ"
